#include <iostream>
#include <ctime>
using namespace std;

int main()
{
	// Declaration section
	int guessNum;
	int number; 
	int guessCount;

 	cout << "Welcome to a guessing game!\n";
	cout << "You will try and guess a number from 1 to 5 randomly generated by the computer.\n";
	cout << "Enter the number of guesses you would like: ";
	cin >> guessCount;
	cout << endl;

	// Guess loop
	for (int i = 0; i < guessCount; i++)
	{
		// Random number generator
		unsigned seed = time(0);
		srand(seed);
		number = 1 + (rand() % 5);

		// Guess input
		cout << "\nEnter your guess: ";
		cin >> guessNum;
		cout << endl;

		// Guess result
		if (guessNum == number)
			{
				cout << "You guessed the correct number!\n";
			}
		else
			{
				cout << "Sorry! That's the wrong number. Try again!\n";
			}
	}	
}