flowchart TD

	mystart[start]
	mystart --> input{num1 and num2 input}
	input --> conditionOp1{operation is +}
	conditionOp1 --> |true| res1[Addition Equation]
	conditionOp1 --> |false| conditionOp2{operation is -}
	conditionOp2 --> |true| res2[Subtraction Equation]
	conditionOp2 --> |false| conditionOp3{operation is *}
	conditionOp3 --> |true| res3[Multiplication Equation]
	conditionOp3 --> |false| conditionOp4{operation is /}
	conditionOp4 --> |true| res4[Division Equation]
	res1 --> end1[Output Statement]
	res2 --> end1
	res3 --> end1
	res4 --> end1