flowchart TD

	mystart[start]
	mystart --> input{input string}
	input --> charFlag1[character is space, punctuation, or digit]
	charFlag1 <--> |true| res1[skip to next character]
	charFlag1 --> |false| res2[char1 = alpha -> change uppercase]
	res2 --> out1[output changed character, go to next letter in orignal string until end of string]
	res2 --> charFlag1
	